name: Test Action CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

# Don't run more than one build per branch
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@8d1f141b985510f36a0376b75b4dc8b0cfc90e8a # v3
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3
        name: Set up Node.js
        with:
          node-version: 16
      - run: |
          npm ci
          npm run build
      - uses: ./
        with:
          message: "test message"
          issue_number: 2
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          COMMENT_IDENTIFIER: "test-output-comment-rewritable-action"
