name: Test Action CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

# Don't run more than one build per branch
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@f947abedefc0d01e4bae344bd7061897ae4e6de9 # v3
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        name: Set up Node.js
        with:
          node-version: 16
      - run: |
          npm ci
          npm run build
      - uses: ./
        with:
          message: "test message"
          issue_number: 2
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          COMMENT_IDENTIFIER: "test-output-comment-rewritable-action"
