name: Test Action CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

# Don't run more than one build per branch
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@df4d23a4977438215339cf0fafceda8d9af8a0e5 # v4
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        name: Set up Node.js
        with:
          node-version: 16
      - run: |
          npm ci
          npm run build
      - uses: ./
        with:
          message: "test message"
          issue_number: 2
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          COMMENT_IDENTIFIER: "test-output-comment-rewritable-action"
